# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 636)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalRegex = QtWidgets.QVBoxLayout()
        self.verticalRegex.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalRegex.setContentsMargins(0, 0, -1, -1)
        self.verticalRegex.setSpacing(5)
        self.verticalRegex.setObjectName("verticalRegex")
        self.regexLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.regexLabel.setFont(font)
        self.regexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.regexLabel.setObjectName("regexLabel")
        self.verticalRegex.addWidget(self.regexLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.importRegexButton = QtWidgets.QPushButton(self.centralwidget)
        self.importRegexButton.setObjectName("importRegexButton")
        self.horizontalLayout.addWidget(self.importRegexButton)
        self.exportRegexButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportRegexButton.setObjectName("exportRegexButton")
        self.horizontalLayout.addWidget(self.exportRegexButton)
        self.convertRegexButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertRegexButton.setObjectName("convertRegexButton")
        self.horizontalLayout.addWidget(self.convertRegexButton)
        self.verticalRegex.addLayout(self.horizontalLayout)
        self.regexInput = QtWidgets.QLineEdit(self.centralwidget)
        self.regexInput.setObjectName("regexInput")
        self.verticalRegex.addWidget(self.regexInput)
        self.verticalLayout.addLayout(self.verticalRegex)
        self.verticalFA1 = QtWidgets.QVBoxLayout()
        self.verticalFA1.setSpacing(5)
        self.verticalFA1.setObjectName("verticalFA1")
        self.automataLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.automataLabel.setFont(font)
        self.automataLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.automataLabel.setObjectName("automataLabel")
        self.verticalFA1.addWidget(self.automataLabel)
        self.horizontalFA1 = QtWidgets.QHBoxLayout()
        self.horizontalFA1.setSpacing(5)
        self.horizontalFA1.setObjectName("horizontalFA1")
        self.importAutomataButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.importAutomataButton.setFont(font)
        self.importAutomataButton.setObjectName("importAutomataButton")
        self.horizontalFA1.addWidget(self.importAutomataButton)
        self.exportAutomataButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exportAutomataButton.setFont(font)
        self.exportAutomataButton.setObjectName("exportAutomataButton")
        self.horizontalFA1.addWidget(self.exportAutomataButton)
        self.convertAutomataButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.convertAutomataButton.setFont(font)
        self.convertAutomataButton.setObjectName("convertAutomataButton")
        self.horizontalFA1.addWidget(self.convertAutomataButton)
        self.verticalFA1.addLayout(self.horizontalFA1)
        self.horizontalFA2 = QtWidgets.QHBoxLayout()
        self.horizontalFA2.setSpacing(5)
        self.horizontalFA2.setObjectName("horizontalFA2")
        self.transitionTable = QtWidgets.QTableWidget(self.centralwidget)
        self.transitionTable.setObjectName("transitionTable")
        self.transitionTable.setColumnCount(0)
        self.transitionTable.setRowCount(0)
        self.horizontalFA2.addWidget(self.transitionTable)
        self.verticalFA2 = QtWidgets.QVBoxLayout()
        self.verticalFA2.setContentsMargins(0, 0, -1, -1)
        self.verticalFA2.setSpacing(5)
        self.verticalFA2.setObjectName("verticalFA2")
        self.addStateButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addStateButton.setFont(font)
        self.addStateButton.setObjectName("addStateButton")
        self.verticalFA2.addWidget(self.addStateButton)
        self.removeStateButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeStateButton.setFont(font)
        self.removeStateButton.setObjectName("removeStateButton")
        self.verticalFA2.addWidget(self.removeStateButton)
        self.addSymbolButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addSymbolButton.setFont(font)
        self.addSymbolButton.setObjectName("addSymbolButton")
        self.verticalFA2.addWidget(self.addSymbolButton)
        self.removeSymbolButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeSymbolButton.setFont(font)
        self.removeSymbolButton.setObjectName("removeSymbolButton")
        self.verticalFA2.addWidget(self.removeSymbolButton)
        self.setFinalStatesButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setFinalStatesButton.setFont(font)
        self.setFinalStatesButton.setObjectName("setFinalStatesButton")
        self.verticalFA2.addWidget(self.setFinalStatesButton)
        self.enumerateButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enumerateButton.setFont(font)
        self.enumerateButton.setObjectName("enumerateButton")
        self.verticalFA2.addWidget(self.enumerateButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalFA2.addItem(spacerItem)
        self.horizontalFA2.addLayout(self.verticalFA2)
        self.verticalFA1.addLayout(self.horizontalFA2)
        self.horizontalFA3 = QtWidgets.QHBoxLayout()
        self.horizontalFA3.setObjectName("horizontalFA3")
        self.checkStringInput = QtWidgets.QLineEdit(self.centralwidget)
        self.checkStringInput.setObjectName("checkStringInput")
        self.horizontalFA3.addWidget(self.checkStringInput)
        self.checkStringButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkStringButton.setFont(font)
        self.checkStringButton.setObjectName("checkStringButton")
        self.horizontalFA3.addWidget(self.checkStringButton)
        self.verticalFA1.addLayout(self.horizontalFA3)
        self.verticalLayout.addLayout(self.verticalFA1)
        self.verticalGr1 = QtWidgets.QVBoxLayout()
        self.verticalGr1.setObjectName("verticalGr1")
        self.grammarLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.grammarLabel.setFont(font)
        self.grammarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.grammarLabel.setObjectName("grammarLabel")
        self.verticalGr1.addWidget(self.grammarLabel)
        self.horizontalGr1 = QtWidgets.QHBoxLayout()
        self.horizontalGr1.setObjectName("horizontalGr1")
        self.importGrammarButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.importGrammarButton.setFont(font)
        self.importGrammarButton.setObjectName("importGrammarButton")
        self.horizontalGr1.addWidget(self.importGrammarButton)
        self.exportGrammarButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exportGrammarButton.setFont(font)
        self.exportGrammarButton.setObjectName("exportGrammarButton")
        self.horizontalGr1.addWidget(self.exportGrammarButton)
        self.convertGrammarButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.convertGrammarButton.setFont(font)
        self.convertGrammarButton.setObjectName("convertGrammarButton")
        self.horizontalGr1.addWidget(self.convertGrammarButton)
        self.verticalGr1.addLayout(self.horizontalGr1)
        self.horizontalGr2 = QtWidgets.QHBoxLayout()
        self.horizontalGr2.setObjectName("horizontalGr2")
        self.productionList = QtWidgets.QListWidget(self.centralwidget)
        self.productionList.setObjectName("productionList")
        self.horizontalGr2.addWidget(self.productionList)
        self.verticalGr2 = QtWidgets.QVBoxLayout()
        self.verticalGr2.setObjectName("verticalGr2")
        self.addProdButton = QtWidgets.QPushButton(self.centralwidget)
        self.addProdButton.setObjectName("addProdButton")
        self.verticalGr2.addWidget(self.addProdButton)
        self.removeProdButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeProdButton.setObjectName("removeProdButton")
        self.verticalGr2.addWidget(self.removeProdButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalGr2.addItem(spacerItem1)
        self.horizontalGr2.addLayout(self.verticalGr2)
        self.verticalGr1.addLayout(self.horizontalGr2)
        self.verticalLayout.addLayout(self.verticalGr1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 545, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuRegular_Language_Operations = QtWidgets.QMenu(self.menuBar)
        self.menuRegular_Language_Operations.setObjectName("menuRegular_Language_Operations")
        self.menuFinite_Automata_Operations = QtWidgets.QMenu(self.menuBar)
        self.menuFinite_Automata_Operations.setObjectName("menuFinite_Automata_Operations")
        MainWindow.setMenuBar(self.menuBar)
        self.actionIntersection = QtWidgets.QAction(MainWindow)
        self.actionIntersection.setObjectName("actionIntersection")
        self.actionDifference = QtWidgets.QAction(MainWindow)
        self.actionDifference.setObjectName("actionDifference")
        self.actionReverse = QtWidgets.QAction(MainWindow)
        self.actionReverse.setObjectName("actionReverse")
        self.actionDeterminize = QtWidgets.QAction(MainWindow)
        self.actionDeterminize.setObjectName("actionDeterminize")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionUnion = QtWidgets.QAction(MainWindow)
        self.actionUnion.setObjectName("actionUnion")
        self.actionConcatenation = QtWidgets.QAction(MainWindow)
        self.actionConcatenation.setObjectName("actionConcatenation")
        self.actionClosure = QtWidgets.QAction(MainWindow)
        self.actionClosure.setObjectName("actionClosure")
        self.menuRegular_Language_Operations.addAction(self.actionUnion)
        self.menuRegular_Language_Operations.addAction(self.actionConcatenation)
        self.menuRegular_Language_Operations.addAction(self.actionClosure)
        self.menuRegular_Language_Operations.addAction(self.actionIntersection)
        self.menuRegular_Language_Operations.addAction(self.actionDifference)
        self.menuRegular_Language_Operations.addAction(self.actionReverse)
        self.menuFinite_Automata_Operations.addAction(self.actionDeterminize)
        self.menuFinite_Automata_Operations.addAction(self.actionMinimize)
        self.menuBar.addAction(self.menuRegular_Language_Operations.menuAction())
        self.menuBar.addAction(self.menuFinite_Automata_Operations.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.regexLabel.setText(_translate("MainWindow", "Regex"))
        self.importRegexButton.setText(_translate("MainWindow", "Import Regex"))
        self.exportRegexButton.setText(_translate("MainWindow", "Export Regex"))
        self.convertRegexButton.setText(_translate("MainWindow", "Convert to Automata"))
        self.automataLabel.setText(_translate("MainWindow", "Automata"))
        self.importAutomataButton.setText(_translate("MainWindow", "Import Automata"))
        self.exportAutomataButton.setText(_translate("MainWindow", "Export Automata"))
        self.convertAutomataButton.setText(_translate("MainWindow", "Convert to Grammar"))
        self.addStateButton.setText(_translate("MainWindow", "Add State"))
        self.removeStateButton.setText(_translate("MainWindow", "Remove State"))
        self.addSymbolButton.setText(_translate("MainWindow", "Add Symbol"))
        self.removeSymbolButton.setText(_translate("MainWindow", "Remove Symbol"))
        self.setFinalStatesButton.setText(_translate("MainWindow", "Set Final States"))
        self.enumerateButton.setText(_translate("MainWindow", "Enumerate"))
        self.checkStringButton.setText(_translate("MainWindow", "Check String"))
        self.grammarLabel.setText(_translate("MainWindow", "Regular Grammar"))
        self.importGrammarButton.setText(_translate("MainWindow", "Import Grammar"))
        self.exportGrammarButton.setText(_translate("MainWindow", "Export Grammar"))
        self.convertGrammarButton.setText(_translate("MainWindow", "Convert To Automata"))
        self.addProdButton.setText(_translate("MainWindow", "Add Production"))
        self.removeProdButton.setText(_translate("MainWindow", "Remove Production"))
        self.menuRegular_Language_Operations.setTitle(_translate("MainWindow", "Regular Language Operations"))
        self.menuFinite_Automata_Operations.setTitle(_translate("MainWindow", "Finite Automata Operations"))
        self.actionIntersection.setText(_translate("MainWindow", "Intersection"))
        self.actionDifference.setText(_translate("MainWindow", "Difference"))
        self.actionReverse.setText(_translate("MainWindow", "Reverse"))
        self.actionDeterminize.setText(_translate("MainWindow", "Determinize"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionUnion.setText(_translate("MainWindow", "Union"))
        self.actionConcatenation.setText(_translate("MainWindow", "Concatenation"))
        self.actionClosure.setText(_translate("MainWindow", "Closure"))

