# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalRe = QtWidgets.QHBoxLayout()
        self.horizontalRe.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalRe.setContentsMargins(0, 0, -1, -1)
        self.horizontalRe.setSpacing(5)
        self.horizontalRe.setObjectName("horizontalRe")
        self.reLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reLabel.setFont(font)
        self.reLabel.setObjectName("reLabel")
        self.horizontalRe.addWidget(self.reLabel)
        self.reInput = QtWidgets.QLineEdit(self.centralwidget)
        self.reInput.setObjectName("reInput")
        self.horizontalRe.addWidget(self.reInput)
        self.convertReButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.convertReButton.setFont(font)
        self.convertReButton.setObjectName("convertReButton")
        self.horizontalRe.addWidget(self.convertReButton)
        self.verticalLayout.addLayout(self.horizontalRe)
        self.verticalFA1 = QtWidgets.QVBoxLayout()
        self.verticalFA1.setSpacing(5)
        self.verticalFA1.setObjectName("verticalFA1")
        self.automataLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.automataLabel.setFont(font)
        self.automataLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.automataLabel.setObjectName("automataLabel")
        self.verticalFA1.addWidget(self.automataLabel)
        self.horizontalFA1 = QtWidgets.QHBoxLayout()
        self.horizontalFA1.setSpacing(5)
        self.horizontalFA1.setObjectName("horizontalFA1")
        self.importFAButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.importFAButton.setFont(font)
        self.importFAButton.setObjectName("importFAButton")
        self.horizontalFA1.addWidget(self.importFAButton)
        self.exportFAButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exportFAButton.setFont(font)
        self.exportFAButton.setObjectName("exportFAButton")
        self.horizontalFA1.addWidget(self.exportFAButton)
        self.convertFAButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.convertFAButton.setFont(font)
        self.convertFAButton.setObjectName("convertFAButton")
        self.horizontalFA1.addWidget(self.convertFAButton)
        self.verticalFA1.addLayout(self.horizontalFA1)
        self.horizontalFA2 = QtWidgets.QHBoxLayout()
        self.horizontalFA2.setSpacing(5)
        self.horizontalFA2.setObjectName("horizontalFA2")
        self.transitionTable = QtWidgets.QTableWidget(self.centralwidget)
        self.transitionTable.setObjectName("transitionTable")
        self.transitionTable.setColumnCount(0)
        self.transitionTable.setRowCount(0)
        self.horizontalFA2.addWidget(self.transitionTable)
        self.verticalFA2 = QtWidgets.QVBoxLayout()
        self.verticalFA2.setContentsMargins(0, 0, -1, -1)
        self.verticalFA2.setSpacing(5)
        self.verticalFA2.setObjectName("verticalFA2")
        self.addStateButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addStateButton.setFont(font)
        self.addStateButton.setObjectName("addStateButton")
        self.verticalFA2.addWidget(self.addStateButton)
        self.removeStatteButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeStatteButton.setFont(font)
        self.removeStatteButton.setObjectName("removeStatteButton")
        self.verticalFA2.addWidget(self.removeStatteButton)
        self.addSymbolButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addSymbolButton.setFont(font)
        self.addSymbolButton.setObjectName("addSymbolButton")
        self.verticalFA2.addWidget(self.addSymbolButton)
        self.removeSymbolButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeSymbolButton.setFont(font)
        self.removeSymbolButton.setObjectName("removeSymbolButton")
        self.verticalFA2.addWidget(self.removeSymbolButton)
        self.toggleFinalStateButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toggleFinalStateButton.setFont(font)
        self.toggleFinalStateButton.setObjectName("toggleFinalStateButton")
        self.verticalFA2.addWidget(self.toggleFinalStateButton)
        self.enumerateButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enumerateButton.setFont(font)
        self.enumerateButton.setObjectName("enumerateButton")
        self.verticalFA2.addWidget(self.enumerateButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalFA2.addItem(spacerItem)
        self.horizontalFA2.addLayout(self.verticalFA2)
        self.verticalFA1.addLayout(self.horizontalFA2)
        self.horizontalFA3 = QtWidgets.QHBoxLayout()
        self.horizontalFA3.setObjectName("horizontalFA3")
        self.checkStringInput = QtWidgets.QLineEdit(self.centralwidget)
        self.checkStringInput.setObjectName("checkStringInput")
        self.horizontalFA3.addWidget(self.checkStringInput)
        self.checkStringButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkStringButton.setFont(font)
        self.checkStringButton.setObjectName("checkStringButton")
        self.horizontalFA3.addWidget(self.checkStringButton)
        self.verticalFA1.addLayout(self.horizontalFA3)
        self.verticalLayout.addLayout(self.verticalFA1)
        self.verticalGr1 = QtWidgets.QVBoxLayout()
        self.verticalGr1.setObjectName("verticalGr1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalGr1.addWidget(self.label)
        self.horizontalGr1 = QtWidgets.QHBoxLayout()
        self.horizontalGr1.setObjectName("horizontalGr1")
        self.importGrButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.importGrButton.setFont(font)
        self.importGrButton.setObjectName("importGrButton")
        self.horizontalGr1.addWidget(self.importGrButton)
        self.exportGrButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exportGrButton.setFont(font)
        self.exportGrButton.setObjectName("exportGrButton")
        self.horizontalGr1.addWidget(self.exportGrButton)
        self.convertGrButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.convertGrButton.setFont(font)
        self.convertGrButton.setObjectName("convertGrButton")
        self.horizontalGr1.addWidget(self.convertGrButton)
        self.verticalGr1.addLayout(self.horizontalGr1)
        self.horizontalGr2 = QtWidgets.QHBoxLayout()
        self.horizontalGr2.setObjectName("horizontalGr2")
        self.productionList = QtWidgets.QListWidget(self.centralwidget)
        self.productionList.setObjectName("productionList")
        self.horizontalGr2.addWidget(self.productionList)
        self.verticalGr2 = QtWidgets.QVBoxLayout()
        self.verticalGr2.setObjectName("verticalGr2")
        self.addProdButton = QtWidgets.QPushButton(self.centralwidget)
        self.addProdButton.setObjectName("addProdButton")
        self.verticalGr2.addWidget(self.addProdButton)
        self.removeProdButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeProdButton.setObjectName("removeProdButton")
        self.verticalGr2.addWidget(self.removeProdButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalGr2.addItem(spacerItem1)
        self.horizontalGr2.addLayout(self.verticalGr2)
        self.verticalGr1.addLayout(self.horizontalGr2)
        self.verticalLayout.addLayout(self.verticalGr1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuGrammar_Operations = QtWidgets.QMenu(self.menuBar)
        self.menuGrammar_Operations.setObjectName("menuGrammar_Operations")
        self.menuRegular_Language_Operations = QtWidgets.QMenu(self.menuBar)
        self.menuRegular_Language_Operations.setObjectName("menuRegular_Language_Operations")
        self.menuFinite_Automata_Operations = QtWidgets.QMenu(self.menuBar)
        self.menuFinite_Automata_Operations.setObjectName("menuFinite_Automata_Operations")
        MainWindow.setMenuBar(self.menuBar)
        self.actionUnion = QtWidgets.QAction(MainWindow)
        self.actionUnion.setObjectName("actionUnion")
        self.actionConcatenation = QtWidgets.QAction(MainWindow)
        self.actionConcatenation.setObjectName("actionConcatenation")
        self.actionInstersection = QtWidgets.QAction(MainWindow)
        self.actionInstersection.setObjectName("actionInstersection")
        self.actionDifference = QtWidgets.QAction(MainWindow)
        self.actionDifference.setObjectName("actionDifference")
        self.actionReverse = QtWidgets.QAction(MainWindow)
        self.actionReverse.setObjectName("actionReverse")
        self.actionDeterminize = QtWidgets.QAction(MainWindow)
        self.actionDeterminize.setObjectName("actionDeterminize")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.menuGrammar_Operations.addAction(self.actionUnion)
        self.menuGrammar_Operations.addAction(self.actionConcatenation)
        self.menuRegular_Language_Operations.addAction(self.actionInstersection)
        self.menuRegular_Language_Operations.addAction(self.actionDifference)
        self.menuRegular_Language_Operations.addAction(self.actionReverse)
        self.menuFinite_Automata_Operations.addAction(self.actionDeterminize)
        self.menuFinite_Automata_Operations.addAction(self.actionMinimize)
        self.menuBar.addAction(self.menuGrammar_Operations.menuAction())
        self.menuBar.addAction(self.menuRegular_Language_Operations.menuAction())
        self.menuBar.addAction(self.menuFinite_Automata_Operations.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reLabel.setText(_translate("MainWindow", "Regular Expression:"))
        self.convertReButton.setText(_translate("MainWindow", "Convert To Automata"))
        self.automataLabel.setText(_translate("MainWindow", "Automata"))
        self.importFAButton.setText(_translate("MainWindow", "Import Automata"))
        self.exportFAButton.setText(_translate("MainWindow", "Export Automata"))
        self.convertFAButton.setText(_translate("MainWindow", "Convert to Grammar"))
        self.addStateButton.setText(_translate("MainWindow", "Add State"))
        self.removeStatteButton.setText(_translate("MainWindow", "Remove State"))
        self.addSymbolButton.setText(_translate("MainWindow", "Add Symbol"))
        self.removeSymbolButton.setText(_translate("MainWindow", "Remove Symbol"))
        self.toggleFinalStateButton.setText(_translate("MainWindow", "Toggle Final State"))
        self.enumerateButton.setText(_translate("MainWindow", "Enumerate"))
        self.checkStringButton.setText(_translate("MainWindow", "Check String"))
        self.label.setText(_translate("MainWindow", "Grammar"))
        self.importGrButton.setText(_translate("MainWindow", "Import Grammar"))
        self.exportGrButton.setText(_translate("MainWindow", "Export Grammar"))
        self.convertGrButton.setText(_translate("MainWindow", "Convert To Automata"))
        self.addProdButton.setText(_translate("MainWindow", "Add Production"))
        self.removeProdButton.setText(_translate("MainWindow", "Remove Production"))
        self.menuGrammar_Operations.setTitle(_translate("MainWindow", "Grammar Operations"))
        self.menuRegular_Language_Operations.setTitle(_translate("MainWindow", "Regular Language Operations"))
        self.menuFinite_Automata_Operations.setTitle(_translate("MainWindow", "Finite Automata Operations"))
        self.actionUnion.setText(_translate("MainWindow", "Union"))
        self.actionConcatenation.setText(_translate("MainWindow", "Concatenation"))
        self.actionInstersection.setText(_translate("MainWindow", "Instersection"))
        self.actionDifference.setText(_translate("MainWindow", "Difference"))
        self.actionReverse.setText(_translate("MainWindow", "Reverse"))
        self.actionDeterminize.setText(_translate("MainWindow", "Determinize"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))

